name: 'crypto_transform'
version: '1.0.0'
config-version: 2

profile: 'crypto_transform' 

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

models:
  crypto_transform:
    +materialized: view