crypto_transform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: crypto_postgres
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('DB_NAME') }}"
      schema: public
      threads: 4